/*
Modelagem Básica 

 ENTIDADE = TABELA 
 
 CAMPO = ATRIBUTOS
 */

CLIENTE 

NOME - CARACTER (30)
CPF - NUMERO (11)
EMAIL - CARACTER (30)
TELEFONE - CARACTER (30)
ENDERECO - CARACTER (100)
SEXO - CARACTER (1)

/* PROCESSOS DE MODELAGEM*/
/* FASE 01 E FASE 092 - AD ADM DE DADOS*/


MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM
MODELAGEM FÍSICA

/* FASE 03 - DBA / AD */

MODELAGEM FÍSICA - SCRIPTS DE BANCO

/* INICIANDO A MODELAGEM FÍSICA */

/* CRIANDO BANCO DE DADOS */
CREATE DATABASE EXEMPLOS;
CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */

USE PROJETO;	

/* CRIANDO A TABELA DE CLIENTES */

CREATE TABLE CLIENTE(
NOME VARCHAR(30),
SEXO CHAR (1),
EMAIL VARCHAR(30),
TELEFONE VARCHAR(30),
ENDERECO VARCHAR (100),
CPF INT (11)
);

/* VERIFICANDO AS TABELAS DO BANCO*/
SHOW TABLES;

USE EXEMPLOS;
SHOW EXEMPLOS;

USE PROJETO;

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */
DESC CLIENTE;

/* Sintaxe básica de inserção - INSERT INTO TABELA... */

/* FÓRMULA 01 - OMITINDOs AS COLUNAS */

INSERT INTO CLIENTE VALUES('CELIA', 'F', 'CELIA@GMAIL.COM','25078869','RIACHOELO - CENTRO - RIO DE JANEIRO -RJ',541521456);

CREATE DATABASE LIVRARIA;

CREATE TABLE LIVROS(
	LIVRO VARCHAR(100),
	AUTOR VARCHAR (100),
	SEXO CHAR(1),
	PAGINAS INT(5),
	EDITORA VARCHAR(30),
	VALOR FLOAT(10,2),
	UF CHAR(2),
	ANO INT(4)
);


