-- MySQL Script generated by MySQL Workbench
-- Fri Nov 20 16:51:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema fastsemen_en
-- -----------------------------------------------------
 DROP SCHEMA IF EXISTS `fastsemen_en`;
-- -----------------------------------------------------
-- Schema fastsemen_en
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fastsemen_en` DEFAULT CHARACTER SET utf8;
USE `fastsemen_en`;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`comprador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`comprador`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`comprador` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `token_troca_senha` VARCHAR(45) NULL DEFAULT NULL,
  `data_troca_senha` DATETIME NULL DEFAULT NULL,
  `tipo` VARCHAR(20) NOT NULL DEFAULT 'comprador',
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `telefoneEwhatsapp` INT NULL DEFAULT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email` (`email` ASC)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`egua`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`egua`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`egua` (
  `idegua` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `numero_registro` VARCHAR(50) NULL DEFAULT NULL,
  `pelagem` VARCHAR(50) NULL DEFAULT NULL,
  `comprador_iduser` INT NOT NULL,
  PRIMARY KEY (`idegua`),
  INDEX `fk_egua_comprador1_idx` (`comprador_iduser` ASC),
  CONSTRAINT `fk_egua_comprador1` FOREIGN KEY (`comprador_iduser`) REFERENCES `fastsemen_en`.`comprador` (`iduser`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`enderecos_comprador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`enderecos_comprador`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`enderecos_comprador` (
  `idenderecos` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(60) NULL DEFAULT NULL,
  `numero` VARCHAR(5) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `iduser` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idenderecos`),
  INDEX `fk_enderecos_comprador_comprador1_idx` (`iduser` ASC),
  CONSTRAINT `fk_enderecos_comprador_comprador1` FOREIGN KEY (`iduser`) REFERENCES `fastsemen_en`.`comprador` (`iduser`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`vendedor`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`vendedor` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `telefone1` VARCHAR(45) NULL DEFAULT NULL,
  `telefone2` VARCHAR(45) NULL DEFAULT NULL,
  `telefone3` VARCHAR(45) NULL DEFAULT NULL,
  `site` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `token_troca_senha` VARCHAR(45) NULL DEFAULT NULL,
  `data_troca_senha` DATETIME NULL DEFAULT NULL,
  `tipo` VARCHAR(20) NOT NULL DEFAULT 'vendedor',
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email` (`email` ASC)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`garanhao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`garanhao`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`garanhao` (
  `idgaranhao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `detalhes` TINYTEXT NULL DEFAULT NULL,
  `central` INT NOT NULL,
  `preco` FLOAT(10, 2) NOT NULL,
  `dosesDia` INT NOT NULL,
  PRIMARY KEY (`idgaranhao`),
  INDEX `fk_garanhao_user_idx` (`central` ASC) ,
  CONSTRAINT `fk_garanhao_user` FOREIGN KEY (`central`) REFERENCES `fastsemen_en`.`vendedor` (`iduser`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`carrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`carrinho`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`carrinho` (
  `idcarrinho` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `quantidade` INT NULL DEFAULT '1',
  `idegua` INT NOT NULL,
  `idgaranhao` INT NOT NULL,
  `idendereco` INT NOT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `tipo_envio` VARCHAR(45) NULL DEFAULT NULL,
  `chutefee` INT NULL DEFAULT NULL,
  `mes` INT NOT NULL,
  `dia` INT NOT NULL,
  PRIMARY KEY (`idcarrinho`),
  INDEX `fk_comprador_has_garanhao_garanhao1_idx` (`idgaranhao` ASC),
  INDEX `fk_comprador_has_garanhao_comprador1_idx` (`iduser` ASC),
  INDEX `fk_carrinho_egua1_idx` (`idegua` ASC),
  INDEX `fk_carrinho_enderecos_comprador1_idx` (`idendereco` ASC),
  CONSTRAINT `fk_carrinho_egua1` FOREIGN KEY (`idegua`) REFERENCES `fastsemen_en`.`egua` (`idegua`),
  CONSTRAINT `fk_carrinho_enderecos_comprador1` FOREIGN KEY (`idendereco`) REFERENCES `fastsemen_en`.`enderecos_comprador` (`idenderecos`),
  CONSTRAINT `fk_comprador_has_garanhao_comprador1` FOREIGN KEY (`iduser`) REFERENCES `fastsemen_en`.`comprador` (`iduser`),
  CONSTRAINT `fk_comprador_has_garanhao_garanhao1` FOREIGN KEY (`idgaranhao`) REFERENCES `fastsemen_en`.`garanhao` (`idgaranhao`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`tipos_semen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`tipos_semen`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`tipos_semen` (
  `idtipos_semen` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idtipos_semen`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`compras`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`compras` (
  `idcompra` INT NOT NULL AUTO_INCREMENT,
  `vendedor_iduser` INT NOT NULL,
  `comprador_iduser` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `idgaranhao` INT NOT NULL,
  `quantidade` INT NOT NULL DEFAULT '1',
  `idegua` INT NOT NULL,
  `enderecos_comprador_idenderecos` INT NOT NULL,
  `chutefee` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dia` INT NOT NULL,
  `mes` INT NOT NULL,
  `idtipo_semen` INT NOT NULL,
  `tipos_semen_idtipos_semen` INT NOT NULL,
  `adicionais_idadicionais` INT NOT NULL,
  PRIMARY KEY (`idcompra`),
  INDEX `fk_vendedor_has_comprador_comprador1_idx` (`comprador_iduser` ASC),
  INDEX `fk_vendedor_has_comprador_vendedor1_idx` (`vendedor_iduser` ASC),
  INDEX `fk_compras_garanhao1_idx` (`idgaranhao` ASC),
  INDEX `fk_compras_egua1_idx` (`idegua` ASC),
  INDEX `fk_compras_enderecos_comprador2_idx` (`enderecos_comprador_idenderecos` ASC),
  INDEX `fk_compras_tipos_semen1_idx` (`tipos_semen_idtipos_semen` ASC),
  CONSTRAINT `fk_compras_egua1` FOREIGN KEY (`idegua`) REFERENCES `fastsemen_en`.`egua` (`idegua`),
  CONSTRAINT `fk_compras_enderecos_comprador2` FOREIGN KEY (`enderecos_comprador_idenderecos`) REFERENCES `fastsemen_en`.`enderecos_comprador` (`idenderecos`),
  CONSTRAINT `fk_compras_garanhao1` FOREIGN KEY (`idgaranhao`) REFERENCES `fastsemen_en`.`garanhao` (`idgaranhao`),
  CONSTRAINT `fk_vendedor_has_comprador_comprador1` FOREIGN KEY (`comprador_iduser`) REFERENCES `fastsemen_en`.`comprador` (`iduser`),
  CONSTRAINT `fk_vendedor_has_comprador_vendedor1` FOREIGN KEY (`vendedor_iduser`) REFERENCES `fastsemen_en`.`vendedor` (`iduser`),
  CONSTRAINT `fk_compras_tipos_semen1` FOREIGN KEY (`tipos_semen_idtipos_semen`) REFERENCES `fastsemen_en`.`tipos_semen` (`idtipos_semen`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`contato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`contato`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`contato` (
  `idcontato` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `assunto` VARCHAR(45) NOT NULL,
  `mensagem` TEXT NOT NULL,
  PRIMARY KEY (`idcontato`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`cupons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`cupons`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`cupons` (
  `idcupons` INT NOT NULL AUTO_INCREMENT,
  `cupom` VARCHAR(10) NOT NULL,
  `vendedor_iduser` INT NOT NULL,
  `preco` FLOAT(10, 2) NOT NULL,
  PRIMARY KEY (`idcupons`),
  UNIQUE INDEX `cupom_UNIQUE` (`cupom` ASC),
  INDEX `fk_cupons_vendedor1_idx` (`vendedor_iduser` ASC),
  CONSTRAINT `fk_cupons_vendedor1` FOREIGN KEY (`vendedor_iduser`) REFERENCES `fastsemen_en`.`vendedor` (`iduser`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`dias_funcionamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`dias_funcionamento`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`dias_funcionamento` (
  `iddias_funcionamento` INT NOT NULL AUTO_INCREMENT,
  `dia` VARCHAR(2) NULL DEFAULT NULL,
  `mes` VARCHAR(2) NULL DEFAULT NULL,
  `ano` INT(4) NOT NULL,
  `vendedor` INT NOT NULL,
  PRIMARY KEY (`iddias_funcionamento`),
  INDEX `fk_dias_funcionamento_user1_idx` (`vendedor` ASC),
  CONSTRAINT `fk_dias_funcionamento_user1` FOREIGN KEY (`vendedor`) REFERENCES `fastsemen_en`.`vendedor` (`iduser`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`enderecos_vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`enderecos_vendedor`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`enderecos_vendedor` (
  `idenderecos` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(60) NULL DEFAULT NULL,
  `numero` VARCHAR(5) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `iduser` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idenderecos`),
  INDEX `fk_enderecos_vendedor1_idx` (`iduser` ASC),
  CONSTRAINT `fk_enderecos_vendedor1` FOREIGN KEY (`iduser`) REFERENCES `fastsemen_en`.`vendedor` (`iduser`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`imagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`imagens`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`imagens` (
  `idimages` INT NOT NULL AUTO_INCREMENT,
  `diretorio` VARCHAR(45) NOT NULL,
  `garanhao` INT NOT NULL,
  `padrao` INT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idimages`),
  INDEX `fk_images_garanhao1_idx` (`garanhao` ASC),
  CONSTRAINT `fk_images_garanhao1` FOREIGN KEY (`garanhao`) REFERENCES `fastsemen_en`.`garanhao` (`idgaranhao`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`newsletter_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`newsletter_users`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`newsletter_users` (
  `idnewsletter_users` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idnewsletter_users`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`raca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`raca`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`raca` (
  `idraca` INT NOT NULL AUTO_INCREMENT,
  `raca` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idraca`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`raca_cavalo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`raca_cavalo`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`raca_cavalo` (
  `garanhao_idgaranhao` INT NOT NULL,
  `raca_idraca` INT NOT NULL,
  INDEX `fk_raca_cavalo_garanhao1_idx` (`garanhao_idgaranhao` ASC),
  INDEX `fk_raca_cavalo_raca1_idx` (`raca_idraca` ASC),
  CONSTRAINT `fk_raca_cavalo_garanhao1` FOREIGN KEY (`garanhao_idgaranhao`) REFERENCES `fastsemen_en`.`garanhao` (`idgaranhao`),
  CONSTRAINT `fk_raca_cavalo_raca1` FOREIGN KEY (`raca_idraca`) REFERENCES `fastsemen_en`.`raca` (`idraca`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`raca_egua`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`raca_egua`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`raca_egua` (
  `idraca` INT NOT NULL AUTO_INCREMENT,
  `raca` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idraca`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`raca_egua_has_egua`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`raca_egua_has_egua`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`raca_egua_has_egua` (
  `raca_egua_idraca` INT NOT NULL AUTO_INCREMENT,
  `egua_idegua` INT NOT NULL,
  PRIMARY KEY (`raca_egua_idraca`, `egua_idegua`),
  INDEX `fk_raca_egua_has_egua_egua1_idx` (`egua_idegua` ASC),
  INDEX `fk_raca_egua_has_egua_raca_egua1_idx` (`raca_egua_idraca` ASC),
  CONSTRAINT `fk_raca_egua_has_egua_egua1` FOREIGN KEY (`egua_idegua`) REFERENCES `fastsemen_en`.`egua` (`idegua`),
  CONSTRAINT `fk_raca_egua_has_egua_raca_egua1` FOREIGN KEY (`raca_egua_idraca`) REFERENCES `fastsemen_en`.`raca_egua` (`idraca`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`tipos_envio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`tipos_envio`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`tipos_envio` (
  `idtipos_envio` INT NOT NULL AUTO_INCREMENT,
  `tipos` VARCHAR(45) NOT NULL,
  `valor` FLOAT(10, 2) NOT NULL,
  `garanhao_idgaranhao` INT NOT NULL,
  PRIMARY KEY (`idtipos_envio`),
  INDEX `fk_tipos_envio_garanhao1_idx` (`garanhao_idgaranhao` ASC),
  CONSTRAINT `fk_tipos_envio_garanhao1` FOREIGN KEY (`garanhao_idgaranhao`) REFERENCES `fastsemen_en`.`garanhao` (`idgaranhao`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`adiconais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`adiconais`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`adiconais` (
  `idadicionais` INT NOT NULL auto_increment,
  `adicional` VARCHAR(100) NOT NULL,
  `preco` FLOAT(10, 2) NOT NULL,
  `garanhao_idgaranhao` INT NOT NULL,
  PRIMARY KEY (`idadicionais`),
  INDEX `fk_adiconais_garanhao1_idx` (`garanhao_idgaranhao` ASC) ,
  CONSTRAINT `fk_adiconais_garanhao1` FOREIGN KEY (`garanhao_idgaranhao`) REFERENCES `fastsemen_en`.`garanhao` (`idgaranhao`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `fastsemen_en`.`garanhao_prenha_egua`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastsemen_en`.`garanhao_prenha_egua`;
CREATE TABLE IF NOT EXISTS `fastsemen_en`.`garanhao_prenha_egua` (
  `garanhao_idgaranhao` INT NOT NULL,
  `egua_idegua` INT NOT NULL,
  `data` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`garanhao_idgaranhao`, `egua_idegua`),
  INDEX `fk_garanhao_has_egua_egua1_idx` (`egua_idegua` ASC) ,
  INDEX `fk_garanhao_has_egua_garanhao1_idx` (`garanhao_idgaranhao` ASC),
  CONSTRAINT `fk_garanhao_has_egua_garanhao1` FOREIGN KEY (`garanhao_idgaranhao`) REFERENCES `fastsemen_en`.`garanhao` (`idgaranhao`),
  CONSTRAINT `fk_garanhao_has_egua_egua1` FOREIGN KEY (`egua_idegua`) REFERENCES `fastsemen_en`.`egua` (`idegua`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

